esphome:
  name: air-quality-one
  friendly_name: Air Quality One

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "2p1RyTqL2c2qplV+3dL5FHROqVwN6Ualhyb0GT++uU8="

ota:
  password: "52f60abca902eadecfa7b3d622b19919"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Air-Quality-One Fallback Hotspot"
    password: "NkExK53oI8rO"

captive_portal:

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a
  
sensor:
- platform: mics_4514
  nitrogen_dioxide:
    name: Nitrogen Dioxide
  carbon_monoxide:
      name: Carbon Monoxide
  hydrogen:
      name: Hydrogen
  ethanol:
      name: Ethanol
  methane:
    name: Methane
  ammonia:
      name: Ammonia
  update_interval: 30s
